BEGIN;

--СОздание таблицы покупателей
DROP TABLE IF EXISTS CUSTOMERS CASCADE;
CREATE TABLE CUSTOMERS
(
    CUST_ID SERIAL PRIMARY KEY,
    NAME    VARCHAR(255)
);
INSERT INTO CUSTOMERS (NAME)
VALUES ('Jim'),
       ('John'),
       ('Mike');

--Создание таблицы товаров
DROP TABLE IF EXISTS PRODUCTS CASCADE;
CREATE TABLE PRODUCTS
(
    PROD_ID SERIAL PRIMARY KEY,
    TITLE   VARCHAR(255),
    PRICE   numeric(8, 2)
);
INSERT INTO PRODUCTS (TITLE, PRICE)
VALUES ('Sprite', 30.00),
       ('Fanta', 40.00),
       ('Cola', 100.00);

--Создание таблицы истории покупок
DROP TABLE IF EXISTS PURCHASES CASCADE;
CREATE TABLE PURCHASES
(
    CUST_CUST_ID INTEGER,
    PROD_PROD_ID INTEGER,
    FOREIGN KEY (CUST_CUST_ID) REFERENCES CUSTOMERS (CUST_ID),
    FOREIGN KEY (PROD_PROD_ID) REFERENCES PRODUCTS (PROD_ID)
);
INSERT INTO PURCHASES(CUST_CUST_ID, PROD_PROD_ID)
VALUES (1, 1),
       (1, 3),
       (2, 1),
       (2, 2),
       (3, 2);

COMMIT;